"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";
import { getPaper, summarizePaper, ApiError } from "@/lib/api";
import type { PaperDetail } from "@/lib/types";

export default function PaperDetailPage() {
  const params = useParams<{ id: string }>();
  const paperId = params.id;

  const [paper, setPaper] = useState<PaperDetail | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [loadError, setLoadError] = useState<string | null>(null);

  const [summary, setSummary] = useState<string | null>(null);
  const [isSummarizing, setIsSummarizing] = useState(false);
  const [summarizeError, setSummarizeError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    setIsLoading(true);
    setLoadError(null);

    getPaper(paperId)
      .then((data) => {
        if (!cancelled) setPaper(data);
      })
      .catch((err: unknown) => {
        if (cancelled) return;
        setLoadError(err instanceof ApiError ? err.message : "Something went wrong.");
      })
      .finally(() => {
        if (!cancelled) setIsLoading(false);
      });

    return () => {
      cancelled = true;
    };
  }, [paperId]);

  async function handleSummarize() {
    setIsSummarizing(true);
    setSummarizeError(null);
    try {
      const result = await summarizePaper(paperId);
      setSummary(result.summary);
    } catch (err) {
      setSummarizeError(err instanceof ApiError ? err.message : "Something went wrong.");
    } finally {
      setIsSummarizing(false);
    }
  }

  return (
    <main className="mx-auto max-w-3xl px-4 py-10 sm:py-14">
      <Link href="/" className="text-sm text-accent hover:underline">
        &larr; Back to search
      </Link>

      {isLoading && (
        <div className="mt-6 space-y-3" aria-busy="true" aria-label="Loading paper">
          <div className="h-8 w-3/4 animate-pulse rounded border border-border bg-paper-raised" />
          <div className="h-4 w-1/2 animate-pulse rounded border border-border bg-paper-raised" />
          <div className="h-32 animate-pulse rounded border border-border bg-paper-raised" />
        </div>
      )}

      {!isLoading && loadError && (
        <div className="mt-6 rounded-lg border border-error-soft bg-error-soft px-4 py-3 text-sm text-error">
          <p className="font-medium">Couldn&apos;t load this paper</p>
          <p className="mt-0.5">{loadError}</p>
        </div>
      )}

      {!isLoading && !loadError && paper && (
        <article className="mt-6">
          <h1 className="font-serif text-2xl leading-snug text-ink sm:text-3xl">{paper.title}</h1>

          <p className="mt-2 text-ink-muted">
            {paper.authors.length > 0 ? paper.authors.map((a) => a.name).join(", ") : "Authors unknown"}
          </p>

          <div className="mt-3 flex flex-wrap items-center gap-2 text-xs">
            {paper.publication_year && (
              <span className="rounded-full border border-border px-2 py-0.5 text-ink-muted">
                {paper.publication_year}
              </span>
            )}
            <span className="rounded-full border border-border px-2 py-0.5 text-ink-muted">
              {paper.citation_count} {paper.citation_count === 1 ? "citation" : "citations"}
            </span>
            {paper.topics.map((t) => (
              <span key={t.name} className="rounded-full bg-accent-soft px-2 py-0.5 text-accent">
                {t.name}
              </span>
            ))}
          </div>

          {paper.doi && (
            <p className="mt-3 text-sm">
              <a
                href={paper.doi.startsWith("http") ? paper.doi : `https://doi.org/${paper.doi}`}
                target="_blank"
                rel="noopener noreferrer"
                className="text-accent hover:underline"
              >
                View DOI &rarr;
              </a>
            </p>
          )}

          <section className="mt-8">
            <h2 className="font-serif text-lg text-ink">Abstract</h2>
            {paper.abstract ? (
              <p className="mt-2 leading-relaxed text-ink">{paper.abstract}</p>
            ) : (
              <p className="mt-2 text-sm italic text-ink-muted">No abstract available for this paper.</p>
            )}
          </section>

          <section className="mt-8 rounded-lg border border-border bg-paper-raised p-5">
            <h2 className="font-serif text-lg text-ink">Plain-language summary</h2>
            <p className="mt-1 text-xs text-ink-muted">
              Generated by AI (Groq / gpt-oss-20b) - may be imperfect, always check the abstract above.
            </p>

            {!summary && (
              <button
                onClick={handleSummarize}
                disabled={isSummarizing || !paper.abstract}
                className="mt-3 rounded-md bg-accent px-4 py-2 text-sm font-medium text-white transition hover:bg-accent-hover disabled:cursor-not-allowed disabled:opacity-50"
              >
                {isSummarizing ? "Summarizing..." : "Summarize this paper"}
              </button>
            )}

            {!paper.abstract && (
              <p className="mt-2 text-xs text-ink-muted">This paper has no abstract, so it can&apos;t be summarized.</p>
            )}

            {summarizeError && (
              <div className="mt-3 flex items-center gap-2 rounded-md border border-error-soft bg-error-soft px-3 py-2 text-sm text-error">
                <span>{summarizeError}</span>
                <button onClick={handleSummarize} className="underline hover:no-underline">
                  Try again
                </button>
              </div>
            )}

            {summary && <p className="mt-3 leading-relaxed text-ink">{summary}</p>}
          </section>
        </article>
      )}
    </main>
  );
}